# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
                ('symbol', models.CharField(max_length=3, verbose_name='symbol')),
            ],
            options={
                'verbose_name': 'Waluta',
                'verbose_name_plural': 'Waluty',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euro_rate', models.FloatField(verbose_name='kurs za 1 euro')),
                ('date', models.DateField(verbose_name='data')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.Currency', verbose_name='waluta')),
            ],
            options={
                'verbose_name': 'kurs wymiany',
                'verbose_name_plural': 'kursy wymiany',
            },
        ),
    ]
